module.exports = {
  participacoes: [
    // { rm: 123, atividadeId: 1 }
  ],
  atividades: [
    {
      id: 1,
      nome: "Técnica Pomodoro",
      descricao: "Ciclos de foco de 25 minutos com pausas curtas.",
      duracaoMin: 25,
      categoria: "Produtividade",
      criador: "Sistema",
    },
    {
      id: 2,
      nome: "Meditação Guiada",
      descricao: "Prática de mindfulness por 10 minutos.",
      duracaoMin: 10,
      categoria: "Bem-estar",
      criador: "Sistema",
    },
    {
      id: 3,
      nome: "Alongamento Rápido",
      descricao: "Série de alongamentos para reduzir tensão muscular.",
      duracaoMin: 5,
      categoria: "Saúde Física",
      criador: "Sistema",
    },
    {
      id: 4,
      nome: "Caminhada Curta",
      descricao: "Pequena caminhada para movimentar o corpo.",
      duracaoMin: 15,
      categoria: "Saúde Física",
      criador: "Sistema",
    },
    {
      id: 5,
      nome: "Diário da Gratidão",
      descricao: "Escrever 3 coisas pelas quais você é grato.",
      duracaoMin: 5,
      categoria: "Emocional",
      criador: "Sistema",
    },
    {
      id: 6,
      nome: "Respiração 4-7-8",
      descricao: "Técnica de respiração para reduzir ansiedade.",
      duracaoMin: 3,
      categoria: "Bem-estar",
      criador: "Sistema",
    },
    {
      id: 7,
      nome: "Leitura Breve",
      descricao: "Momento de leitura de 10 minutos.",
      duracaoMin: 10,
      categoria: "Relaxamento",
      criador: "Sistema",
    },
    {
      id: 8,
      nome: "Café Away",
      descricao: "Pausa rápida para café longe da mesa de trabalho.",
      duracaoMin: 10,
      categoria: "Relaxamento",
      criador: "Sistema",
    },
    {
      id: 9,
      nome: "Organização do Dia",
      descricao: "Planejar prioridades e revisar tarefas.",
      duracaoMin: 7,
      categoria: "Produtividade",
      criador: "Sistema",
    },
    {
      id: 10,
      nome: "Alongamento de Pescoço & Ombros",
      descricao: "Exercícios para aliviar tensão acumulada.",
      duracaoMin: 4,
      categoria: "Saúde Física",
      criador: "Sistema",
    },
  ],
};
